### ISSUE TITLE
The Mode 3 cia has some bug that prevents an app from boot

### ISSUE THREAD

**Issue by PocketRotom** [Stary2001/InputRedirection#10]
Basically I want to use PKMN-NTR at my Pkmn Sun. However, sometimes, when I boot the cia of IRM3, the 3DS crashes. It happens when I open NTR or Pkmn Sun. However, there are times that it works and doesn't crash.

**Comment by SkOODaT** [comment]
ive experienced this as well with the new mode3 IR on old 3ds but i was never able to get it to work

**Comment by PocketRotom** [comment]
Try to:
1)Boot IRM3
2)Wait something like 30sec
3)Boot NTR
4)Boot the game.

This method didn't gave me 100% "boot rate" but is a little better

**Comment by Stary2001** [comment]
I managed to reproduce the crash... once. will investigate further :/

@ people who it is crashing for: can you set luma dev options to 'errdisp' and get/upload a crash dump?

**Comment by PocketRotom** [comment]
Can't do that right now. Will do that tomorrow, ok?

**Comment by PocketRotom** [comment]
Here you have two dumps:
https://www.dropbox.com/s/uocvir3rrfphnml/dump.zip?dl=0

**Comment by Stary2001** [comment]
Looks to be the same crash I saw... probably related to app switch somehow :/

**Comment by FateForWindows** [comment]
Yeah, that seems to be what's triggering the crash.

**Comment by MidgeThePidge** [comment]
Do I need to run NTR - 3 along with the Input Redirection - 3?

**Comment by FateForWindows** [comment]
Yes, of course. Just directly open the applications when switching from NTR to InputRedirection. Also, why use this when it's been implemented into Luma?

**Comment by MidgeThePidge** [comment]
Luma doesn't work on extended memory games.

**Comment by Stary2001** [comment]
Luma _should_ work with ext-mem games, and the built in feature is cleaner/has c-stick etc etc. please use that.
