### ISSUE TITLE
[Question] Am I doing this correctly?

### ISSUE THREAD

**Issue by greenDarkness** [Stary2001/InputRedirection#12]
>Install the input_proc cia on your 3ds, then run the injector.
Did InputRedirection_mode3.cia replace input_proc cia? I can't get this working on my Old3DS. 

After launching InputRedirection_mode3.cia and then pressing home, I attempt to launch NTR-mode3.cia. My 3ds then freezes and says that an error has occured. Did I skip a step somewhere?

Thanks for reading!

**Comment by Stary2001** [comment]
Are you using Luma3DS? If so, can you set your developer options to 'ErrDisp' and upload the resulting crash dump?

(also, that should be fine...)

**Comment by greenDarkness** [comment]
UPDATE: I was doing it wrong. I was launching input redirection before NTR. I am using Luma3DS, and if the order was irrelevant then I can get you a crash dump.

**Comment by Stary2001** [comment]
should be fine now, thanks
