### ISSUE TITLE
when using x360ce + wii u usb gcn adapter makes the L button act as start along with the start button

### ISSUE THREAD

**Issue by masterspike52** [Stary2001/InputRedirection#13]

**Comment by Stary2001** [comment]
can you verify that this issue does not occur in other applications? also, check the key mappings in whatever client application you're using.

**Comment by masterspike52** [comment]
when you say applications, do you mean other 3ds applications or computer applications, cause computer applications it works for really anything that isnt an emulator i.e. dolphin, pj64, etc.... but i havent tried it with other games for the 3ds
