### ISSUE TITLE
InputProc (Go Away version) shares same titleid as PersonaQ

### ISSUE THREAD

**Issue by ElderCub** [Stary2001/InputRedirection#3]
From what I understand, this is an older or obsolete version of InputProc, however it is still on Homebr3w. If you could either request to have it taken down, or fix it's titleid, that would be good so that no one makes the same mistake I have.

**Comment by Stary2001** [comment]
yep it's obsolete by now. not my repo that has the broken release, go complain at Kazo
(that entire fork is obsolete by now, all the changes are merged anyway...)
https://github.com/Kazo/InputRedirection

**Comment by ElderCub** [comment]
Ah sorry, didn't who it was. Will do.
