### ISSUE TITLE
Doesn't work while inside System Settings

### ISSUE THREAD

**Issue by 3096** [Stary2001/InputRedirection#4]
Any idea why?

**Comment by Stary2001** [comment]
MSET does odd things - will chalk it up to my process running on the appcore. The NTR Debugger method should still work, however.
(opened #5 to track a better persistence method.)

**Comment by Stary2001** [comment]
HBL mode gone.

**Comment by 3096** [comment]
Wait but NTR doesn't work either...

**Comment by Stary2001** [comment]
~~oh... ntr works on n3ds, but not on o3ds :/~~
launch standard bootntr, then launch system settings. make sure you're using latest NTR. just tested on 2ds

**Comment by 3096** [comment]
That's odd because I was testing it on n3ds too

**Comment by Stary2001** [comment]
it works fine for me on n3ds *shrug*

**Comment by 3096** [comment]
wait... doesn't the 3ds disconnect wifi when in system setting?

**Comment by Stary2001** [comment]
that would be it... i just tested ntr works

someone will have to come up with a patch or something to stop mset disabling wifi :/
