### ISSUE TITLE
HBL Version stuck on Nintendo 3DS Screen that shows after boot any application

### ISSUE THREAD

**Issue by PocketRotom** [Stary2001/InputRedirection#6]
I'm trying to boot the HBL Version but it stucks on that screen. Luma (latest stable) + Sysnand (Latest FW)

**Comment by Stary2001** [comment]
Use the 3dsx to launch it - cia is a background process. should probably make this a bit more clear...

**Comment by PocketRotom** [comment]
Thanks. It worked. Maybe, why not, create a Wiki?
