### ISSUE TITLE
Issue When Using Controller with Xpadder

### ISSUE THREAD

**Issue by Pixlet** [Stary2001/InputRedirection#7]
If I have configured a controller to emulate my keyboard using XPadder, when I press a button to control my 3DS, it acts as if left is being pushed on the circle pad, no input can over ride it.

**Comment by Stary2001** [comment]
Which client and which connection type are you using? (Kazo's client / my SDL client, NTR or standard).

**Comment by Pixlet** [comment]
1. Using Kazo's Client
2. Using the NTR version

**Comment by Stary2001** [comment]
is it specifically only left or left/up? i had a similar problem when the input register wasn't initialised properly so it thought all buttons were held down

**Comment by Pixlet** [comment]
Yes, it's always left

**Comment by Stary2001** [comment]
No response, closing.

**Comment by Pixlet** [comment]
I responded...? 
![chrome_2017-02-13_16-51-12](https://cloud.githubusercontent.com/assets/24767729/22905032/b18292b6-f20c-11e6-8c4d-f4275113880e.png)

**Comment by Stary2001** [comment]
it's likely not an issue with inputredirection - double check your bindings, make sure it occurs in only this program etc

i don't have xpadder (or a controller), so i can't test this

i also don't have anything to do with Kazo and didn't contribute to his client..

**Comment by Pixlet** [comment]
Bindings are correct, works with other applications. 

I managed to fix it by using Kit-Kit, odd

Thanks for the help
